id: P000672
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9280
  title: འཛམ་གླིང་ཆེན་པོའི་རྒྱས་བཤད་སྣོད་བཅུད་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    3c0dd4275a8c440e8fb1c5af2c5d2b37:
      image_group_id: I1KG9348
      title: ''
      volume_number: 1
      total_pages: 260
